model_list:
  - model_name: x-gpt-5
    litellm_params:
      model: openai-bridge/x-gpt-5
      api_key: os.environ/OPENAI_API_KEY
      allowed_openai_params:
        - reasoning_effort
        - verbosity
        - tools
      default_tools:
        - type: web_search
        - type: mcp
          server_label: tavily
          server_url: "https://mcp.tavily.com/mcp/?tavilyApiKey={TAVILY_API_KEY}"
          require_approval: never
        - type: mcp
          server_label: context7
          server_url: "https://mcp.context7.com/mcp"
          headers:
            CONTEXT7_API_KEY: "{CONTEXT7_API_KEY}"
          require_approval: never
        - type: mcp
          server_label: deepwiki
          server_url: "https://mcp.deepwiki.com/mcp"
          require_approval: never
      outbound_model: gpt-5
      default_verbosity: low
      response_prefix: "Тестовый режим. Нельзя: прикреплять документы и картинки, редактировать и удалять сообщения, перегенерировать ответ, дублировать диалоги, переключать модель. Место для рекламы сдается. Минздрав предупреждает: курение вредит вашему здоровью, лучше бухайте."

  - model_name: x-gpt-5-thinking
    litellm_params:
      model: openai-bridge/x-gpt-5-thinking
      api_key: os.environ/OPENAI_API_KEY
      allowed_openai_params:
        - reasoning_effort
        - verbosity
        - tools
      reasoning_effort: medium
      default_tools:
        - type: web_search
        - type: mcp
          server_label: tavily
          server_url: "https://mcp.tavily.com/mcp/?tavilyApiKey={TAVILY_API_KEY}"
          require_approval: never
        - type: mcp
          server_label: context7
          server_url: "https://mcp.context7.com/mcp"
          headers:
            CONTEXT7_API_KEY: "{CONTEXT7_API_KEY}"
          require_approval: never
        - type: mcp
          server_label: deepwiki
          server_url: "https://mcp.deepwiki.com/mcp"
          require_approval: never
      outbound_model: gpt-5
      default_verbosity: low
      response_prefix: "Тестовый режим. Нельзя: прикреплять документы и картинки, редактировать и удалять сообщения, перегенерировать ответ, дублировать диалоги, переключать модель. Место для рекламы сдается. Минздрав предупреждает: курение вредит вашему здоровью, лучше бухайте."
  
  - model_name: x-gpt-5-thinking-high
    litellm_params:
      model: openai-bridge/x-gpt-5-thinking-high
      api_key: os.environ/OPENAI_API_KEY
      allowed_openai_params:
        - reasoning_effort
        - verbosity
        - tools
      reasoning_effort: high
      default_tools:
        - type: web_search
        - type: mcp
          server_label: tavily
          server_url: "https://mcp.tavily.com/mcp/?tavilyApiKey={TAVILY_API_KEY}"
          require_approval: never
        - type: mcp
          server_label: context7
          server_url: "https://mcp.context7.com/mcp"
          headers:
            CONTEXT7_API_KEY: "{CONTEXT7_API_KEY}"
          require_approval: never
        - type: mcp
          server_label: deepwiki
          server_url: "https://mcp.deepwiki.com/mcp"
          require_approval: never
      outbound_model: gpt-5
      background: true
      default_verbosity: low
      response_prefix: "Тестовый режим. Нельзя: прикреплять документы и картинки, редактировать и удалять сообщения, перегенерировать ответ, дублировать диалоги, переключать модель. Место для рекламы сдается. Минздрав предупреждает: курение вредит вашему здоровью, лучше бухайте."

  - model_name: gpt-5-mini
    litellm_params:
      model: openai/gpt-5-mini
      api_key: os.environ/OPENAI_API_KEY
  
  - model_name: x-o4-mini-deep-research
    litellm_params:
      model: openai-bridge/x-o4-mini-deep-research
      api_key: os.environ/OPENAI_API_KEY
      allowed_openai_params:
        - reasoning_effort
      default_tools:
        - type: web_search_preview
      outbound_model: o4-mini-deep-research
      background: true
      response_prefix: "Тестовый режим. Нельзя: прикреплять документы и картинки, редактировать и удалять сообщения, перегенерировать ответ, дублировать диалоги, переключать модель. Место для рекламы сдается. Минздрав предупреждает: курение вредит вашему здоровью, лучше бухайте."

  - model_name: x-o3-deep-research
    litellm_params:
      model: openai-bridge/x-o3-deep-research
      api_key: os.environ/OPENAI_API_KEY
      allowed_openai_params:
        - reasoning_effort
      default_tools:
        - type: web_search_preview
      outbound_model: o3-deep-research
      background: true
      response_prefix: "Тестовый режим. Нельзя: прикреплять документы и картинки, редактировать и удалять сообщения, перегенерировать ответ, дублировать диалоги, переключать модель. Место для рекламы сдается. Минздрав предупреждает: курение вредит вашему здоровью, лучше бухайте."

  - model_name: x-perplexity-pro
    litellm_params:
      model: perplexity-bridge/x-sonar-pro
      outbound_model: sonar-pro

  - model_name: x-perplexity-pro-high
    litellm_params:
      model: perplexity-bridge/x-sonar-pro-high
      outbound_model: sonar-pro
      web_search_options:
        search_context_size: high

  - model_name: x-perplexity-reasoning-pro
    litellm_params:
      model: perplexity-bridge/x-sonar-reasoning-pro
      allowed_openai_params:
        - reasoning_effort
      reasoning_effort: high
      outbound_model: sonar-reasoning-pro
      cut_think: true

  - model_name: x-perplexity-reasoning-pro-high
    litellm_params:
      model: perplexity-bridge/x-sonar-reasoning-pro-high
      allowed_openai_params:
        - reasoning_effort
      outbound_model: sonar-reasoning-pro
      reasoning_effort: high
      web_search_options:
        search_context_size: high
      cut_think: true

  - model_name: x-perplexity-deep-research
    litellm_params:
      model: perplexity-bridge/x-sonar-deep-research
      allowed_openai_params:
        - reasoning_effort
      outbound_model: sonar-deep-research
      reasoning_effort: high
      cut_think: true

  - model_name: x-perplexity-deep-research-high
    litellm_params:
      model: perplexity-bridge/x-sonar-deep-research-high
      allowed_openai_params:
        - reasoning_effort
      outbound_model: sonar-deep-research
      reasoning_effort: high
      web_search_options:
        search_context_size: high
      cut_think: true

  - model_name: sonar-deep-research
    litellm_params:
      model: perplexity/sonar-deep-research
      api_key: os.environ/PERPLEXITY_API_KEY

  - model_name: sonar-pro
    litellm_params:
      model: perplexity/sonar-pro
      api_key: os.environ/PERPLEXITY_API_KEY

  - model_name: sonar-reasoning-pro
    litellm_params:
      model: perplexity/sonar-reasoning-pro
      api_key: os.environ/PERPLEXITY_API_KEY


litellm_settings:
  custom_provider_map:
    - provider: openai-bridge
      custom_handler: custom_handler.openai_responses_bridge
    - provider: perplexity-bridge
      custom_handler: custom_handler.perplexity_bridge


general_settings:
  enable_preview_features: true
